# Generated by Django 2.2.6 on 2020-01-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.CharField(choices=[('background check', 'background check')], default='background check', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('processed', 'processed'), ('cancelled', 'cancelled')], default='registered', max_length=100),
        ),
    ]
