# Generated by Django 2.2.6 on 2020-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200109_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='charge_id',
            new_name='operation_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_method',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('processed', 'processed'), ('applied', 'applied'), ('cancelled', 'cancelled')], default='registered', max_length=100),
        ),
    ]
