POST localhost:8000/v1/register/
Content-Type: application/json

{
  "email": "idekel.santana@gmail.com",
  "password": "123456",
  "role": "instructor",
  "birthday": "1990-10-24",
  "referringCode": "z6Gu5W6VckRTQoi6",
  "firstName": "Idekel",
  "lastName": "Santana",
  "reference": "facebook",
  "termsAccepted": true,
  "gender": "male",
  "phoneNumber": "+18292901143",
  "location": "Boston MA",
  "lat": "43",
  "lng": "27.6"
}

### Set-Cookie:  csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F; expires=Sat, 22 Aug 2020 11:59:50 GMT; Max-Age=31449600; Path=/; SameSite=Lax
### Set-Cookie:  sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4; expires=Sat, 07 Sep 2019 11:59:50 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax

###

POST localhost:8000/v1/verify-phone/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "phoneNumber": "+18292901143",
  "channel": "sms"
}

###
PUT localhost:8000/v1/verify-phone/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "phoneNumber": "+18292901143",
  "code": "3137"
}

###

PUT localhost:8000/v1/build-profile/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv;csrftoken=JP1OuCkZlrx8PyQVY8CO97XApPuO4OPOv9Bm7nmQWubaWfRVUGsay7PIT6ZaX9ha
Content-Type: application/json
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "bioTitle": "Nice instructor",
  "bioDescription": "Son long text",
  "music": ["something1", "something2", "something3"],
  "yearsOfExperience": 3
}

###

GET localhost:8000/v1/fetch-profile/
{
  "bioTitle": "Nice instructor",
  "bioDescription": "Son long text",
  "music": ["Son long text"]
}

###
POST localhost:8000/v1/build-job-preferences/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
	"instruments": [
    {
      "instrument": "piano",
      "skillLevel": "advanced"
    }
  ],
  "lessonSize": {
    "oneStudent": true,
    "smallGroups": false,
    "largeGroups": false
  },
  "ageGroup": {
    "children": true,
    "teens": false,
    "adults": true,
    "seniors": true
  },
  "rates": {
    "mins30": 50,
    "mins45": 50,
    "mins60": 50,
    "mins90": 50
  },
  "placeForLessons": {
    "home": true,
    "studio": true,
    "online": true
  },
  "availability": {
      "mon8to10": true,
    "mon10to12": false,
    "mon12to3": true
    },
  "qualifications": {
    "certifiedTeacher": true,
    "musicTherapy": false,
    "musicProduction": false,
    "earTraining": false,
    "conducting": false,
    "virtuosoRecognition": false,
    "performance": false,
    "musicTheory": false,
    "youngChildrenExperience": false,
    "repertoireSelection": false
  },
  "languages": ["french", "spanish"],
  "studioAddress": "fpp",
  "travelDistance": "faa"
}

###
POST localhost:8000/v1/login
Content-Type: application/json

{
  "email": "idekel.santana@gmail.com",
  "password": "123456"
}

###

GET localhost:8000/v1/logout
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
Content-Type: application/json

###

GET localhost:8000/v1/csrf-token
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv;csrftoken=JP1OuCkZlrx8PyQVY8CO97XApPuO4OPOv9Bm7nmQWubaWfRVUGsay7PIT6ZaX9ha

###

GET localhost:8000/v1/whoami
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv


###
POST localhost:8000/v1/test
Content-Type: application/json
Cookie: sessionid=mismf58tf7xf0xdajvzqmg159ytcx77p; csrftoken=6Hzd0GrKXQAYuo2W3qwDqHQs7MpQdkYc9iauCTUc7hQG9YoT6L0cTsqY2dPM4CNi
X-CSRFToken: OgoFm0sgQTG3lb7Za4Vl6zlfHLuirIZ8RRZWYdVI0kWL0LtWdppUzkVLCcUei0Oe

{
  "email": "idekel.santana@gmail.com",
  "password": "123456"
}

###

POST localhost:8000/v1/forgot-password/
Content-Type: application/json

{
  "email": "idekel.santana@gmail.com"
}

###

PUT localhost:8000/v1/forgot-password/?token={token}
Content-Type: application/json

{
  "password": "minuevopassword"
}

###

POST localhost:8000/v1/upload_avatar/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

Body: form-data
Key: avatar
Value: file to upload

###

POST localhost:8000/v1/referral_email/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "email": "luisllave12357@gmail.com"
}

###

PUT localhost:8000/v1/student-details/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "instrument": "flaute",
  "skillLevel": "basic",
  "lessonPlace": "home",
  "lessonDuration": "90 mins"
}

###

GET localhost:8000/v1/student-details/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv

###

POST localhost:8000/v1/students/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
    "name": "Joseph",
    "age": 31,
    "instrument": "flaute",
    "skillLevel": "basic",
    "lessonPlace": "home",
    "lessonDuration": "90 mins"
}

###

GET localhost:8000/v1/students/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv

###

PUT localhost:8000/v1/students/3/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "name": "John",
  "age": 41,
  "instrument": "flaute",
  "skillLevel": "basic",
  "lessonPlace": "online",
  "lessonDuration": "60 mins"
}

###

DELETE localhost:8000/v1/students/3/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

###

POST localhost:8000/v1/education/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "school": "Hopkins",
  "graduationYear": 2003,
  "degreeType": "certification",
  "fieldOfStudy": "Math",
  "schoolLocation": "Utah"
}

###

GET localhost:8000/v1/education/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv

###

PUT localhost:8000/v1/education/3/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "school": "Baltimore",
  "graduationYear": 2003,
  "degreeType": "certification",
  "fieldOfStudy": "Math",
  "schoolLocation": "Roosvelt Bv Nro 7"
}

###

DELETE localhost:8000/v1/education/3/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

###

PUT localhost:8000/v1/account-info/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "firstName": "Idekel",
  "lastName": "Santana",
  "middleName": "E.",
  "email": "idekel.santana@gmail.com",
  "gender": "male",
  "location": "725 Adams St Boston MA 02122",
  "lat": "43",
  "long": "27.6"
}

###

POST localhost:8000/v1/employment/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "jobTitle": "Consultor",
  "employer": "Advanced Company Co.",
  "jobLocation": "Houston",
  "fromMonth": "august",
  "fromYear": 2017,
  "stillWorkHere": true
}

###

GET localhost:8000/v1/employment/
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F


###

PUT localhost:8000/v1/employment/3/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "jobTitle": "Staff Assistant",
  "employer": "MyCompany Co.",
  "jobLocation": "NewYork",
  "fromMonth": "october",
  "fromYear": 2014,
  "toMonth": "june",
  "toYear": 2017,
  "stillWorkHere": false
}

###

DELETE localhost:8000/v1/employment/3/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

###

GET localhost:8000/v1/instructors/?distance=80&instruments=piano,guitar&min_rate=10.0&max_rate=14.5&availability=monday,wednesday&placeForLessons=home&studentAges=children,teens&gender=female&languages=english,spanish&qualifications=youngChildrenExperience,earTraining&location=31.1654019,-83.31360716&sort=distance

# GET parameters are optionals. Distance value is in miles, default 50 value is used (when no value is provided)
# sort parameter can take the values: distance, -distance, rate, -rate

###

GET localhost:8000/v1/instructors/1/

###

POST localhost:8000/v1/request-references/

{
   "emails": ["luisllave12357@gmail.com", "luistest2020@yopmail.com"]
}

###

GET localhost:8000/v1/references-list/

###

GET localhost:8000/v1/offers/

###

GET localhost:8000/v1/offers-active/

###

GET localhost:8000/v1/minimal-rate/

###

POST localhost:8000/v1/registration-affiliate/

{
	"firstName": "John",
	"lastName": "Connor",
	"email": "JohnConnor20@yopmail.com",
	"password": "Test123456",
	"birthday": "1997-03-24",
	"companyName": "Enterprise Inc"
}

###

POST localhost:8000/v1/lesson-request/
Content-Type: application/json

{
  "requestTitle": "Guitar Instructor needed in Boston MA",
  "instrument": "guitar",
  "placeForLessons": "home",
  "skillLevel": "beginner",
  "lessonDuration": "45mins",
  "requestMessage": "Hello I am looking for a guitar instructor",
  "maxTravelDistance": 100
}
or
{
  "requestTitle": "Guitar Instructor needed in Boston MA",
  "instrument": "guitar",
  "placeForLessons": "home",
  "skillLevel": "beginner",
  "lessonDuration": "45mins",
  "requestMessage": "Hello I am looking for a guitar instructor",
  "maxTravelDistance": 100,
  "date": "2020-05-22",
  "time": "09:30",
  "timezone": "America/New_York"
}
or
{
  "students": [
    {
      "name": "Santiago",
      "age": 9
    },
    {
      "name": "Teresa",
      "age": 7
    }
  ],
  "requestTitle": "Piano Instructor needed in Boston MA",
  "instrument": "piano",
  "placeForLessons": "home",
  "skillLevel": "beginner",
  "lessonDuration": "60mins",
  "requestMessage": "My twins want to take piano lessons together",
  "maxTravelDistance": 100
}

###

PUT localhost:8000/v1/lesson-request/1/
Content-Type: application/json

# same data as required in POST method

###

DELETE localhost:8000/v1/lesson-request/1/

###

GET localhost:8000/v1/lesson-request/1/

###

GET localhost:8000/v1/lesson-request/

###

POST localhost:8000/v1/applications/
Content-Type: application/json

{
  "requestId": 1,
  "rate": "30.00",
  "message": "Hello, I'm available for teaching lessons"
}

###

GET localhost:8000/v1/applications/

###

GET localhost:8000/v1/lesson-request-list/?instrument=piano&placeForLessons=home&distance=30&location=25.6514,-65.3702&age=child

# GET parameters are optionals. Distance value is in miles, default 50 value will be used (when location value is provided)
# location value has the format: latitude,longitude

###

GET localhost:8000/v1/lesson-request-item/1/

###

POST localhost:8000/v1/background-check-request/

{
"instructorId": 2,
"amount": 15.75,
"stripeToken": "tok_1EpRgYK2gfFa5B9C2sn4L0kG"
}

# instructorId is optional, when is not provided, data is obtained from logged user

###

GET localhost:8000/v1/background-check-request/?instructorId=1

# instructorId is optional, when is not provided, data is obtained from logged user
# Note: this endpoint returns status from DB

###

GET localhost:8000/v1/background-check-status/?instructorId=1

# instructorId parameter is optional, when is not provided, data is obtained from logged user
# Note: this endpoint make a call to Provider API and change status in DB if required

###

GET localhost:8000/v1/application-list/1/

# Note: the id value is lesson_request_id

###

GET localhost:8000/v1/booking-data/1/

# Note: the id value is application_id

###

POST localhost:8000/v1/booking-data/1/

{
"package": "maestro"
}

# Note: the id value is application_id

###

POST localhost:8000/v1/confirm-booking/

{
	"applicationId": 1,
	"package": "maestro",
	"paymentMethodCode": "pm_1GZ1RNKKgfFa5BBCGeLVyC0r"
}

###

GET localhost:8000/v1/dashboard/

###

GET localhost:8000/v1/referral-info/WVG3Kw4HaDhEpyag/

# Note: WVG3Kw4HaDhEpyag is the referral_token of an existing user

###

GET localhost:8000/v1/referral-dashboard/

###

GET localhost:8000/timezones/

###

POST localhost:8000/lessons/

{
"bookingId": 8,
"date": "2020-05-18",
"time": "15:30",
"timezone": "America/New_York"
}

###

PUT localhost:8000/lessons/<lesson_id>/

{
"date": "2020-05-18",
"time": "17:30",
"timezone": "America/New_York"
}
or
{
"grade": 2,
"comment": "Good work!"
}
or
{
"status": "missed"
}

###

GET localhost:8000/lessons/<lesson_id>/

###

POST localhost:8000/v1/sign-file/
Content-Type: application/json

{
	"user_id": 5,
	"file_name": "video0.flv",
	"file_type": "video/x-flv"
}

###

POST localhost:8000/upload-video-profile/

{
"video": "https://nabi-test.s3.amazonaws.com/media/videos/user_5/video.flv"
}

###
