POST localhost:8000/v1/register/
Content-Type: application/json

{
  "email": "idekel.santana@gmail.com",
  "password": "123456",
  "role": "instructor",
  "birthday": "1990-10-24",
  "referring_code": "z6Gu5W6VckRTQoi6"
}

### Set-Cookie:  csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F; expires=Sat, 22 Aug 2020 11:59:50 GMT; Max-Age=31449600; Path=/; SameSite=Lax
### Set-Cookie:  sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4; expires=Sat, 07 Sep 2019 11:59:50 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax

PUT localhost:8000/v1/account-info/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "first_name": "Idekel",
  "last_name": "Santana",
  "middle_name": "Paola",
  "gender": "male",
  "location": "725 Adams St Boston MA 02122",
  "lat": "6516516",
  "lng": "6516516"
}

###
POST localhost:8000/v1/verify-phone/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "phone_number": "+18292901143",
  "channel": "sms"
}

###
PUT localhost:8000/v1/verify-phone/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
  "phone_number": "+18292901143",
  "code": "3137"
}

###

PUT localhost:8000/v1/build-profile/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv;csrftoken=JP1OuCkZlrx8PyQVY8CO97XApPuO4OPOv9Bm7nmQWubaWfRVUGsay7PIT6ZaX9ha
Content-Type: application/json
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "bio_title": "Nice instructor",
  "bio_description": "Son long text",
  "music": ["Son long text"]
}

###

GET localhost:8000/v1/fetch-profile/
{
  "bio_title": "Nice instructor",
  "bio_description": "Son long text",
  "music": ["Son long text"]
}

###
POST localhost:8000/v1/build-job-preferences/
Content-Type: application/json
Cookie: sessionid=65vw4w0a116tfnzcjdcb4ka7dhhpqnu4;csrftoken=zDbcXUdR4RCvgb7XwRP64VgW69EUc0OJSm3OosxdhgFVVuPKUWGaExApLaXBsb6F
X-CSRFToken: 8LUV70LbEX0JeWQFfd8N3XTzdH105FTjruMxyy5xRm39TfysDiZRDzd2SIkHlQbf

{
	"instruments": [
    {
      "instrument": "piano",
      "skillLevel": "advanced"
    }
  ],
  "lesson_size": {
    "one_student": true,
    "small_groups": false,
    "large_groups": false
  },
  "age_group": {
    "children": true,
    "teens": false,
    "adults": true,
    "seniors": true
  },
  "lesson_rate": {
    "mins30": 50,
    "mins45": 50,
    "mins60": 50,
    "mins90": 50
  },
  "place_for_lessons": {
    "home": true,
    "studio": true,
    "online": true
  },
  "availability": [
    {
      "mon8to10": true,
    "mon10to12": false,
    "mon12to3": true
    }
  ],
  "additional_qualifications": {
    "certified_teacher": true,
    "music_therapy": false,
    "music_production": false,
    "ear_training": false,
    "conducting": false,
    "virtuoso_recognition": false,
    "performance": false,
    "music_theory": false,
    "young_children_experience": false,
    "repertoire_selection": false
  },
  "languages": ["french", "spanish"],
  "studio_address": "fpp",
  "travel_distance": "faa"
}

###
POST localhost:8000/v1/login
Content-Type: application/json

{
  "email": "idekel.santana@gmail.com",
  "password": "123456"
}

###

GET localhost:8000/v1/logout
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
Content-Type: application/json

###

GET localhost:8000/v1/csrf-token
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv;csrftoken=JP1OuCkZlrx8PyQVY8CO97XApPuO4OPOv9Bm7nmQWubaWfRVUGsay7PIT6ZaX9ha

###

GET localhost:8000/v1/whoami
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv


###
POST localhost:8000/v1/test
Content-Type: application/json
Cookie: sessionid=mismf58tf7xf0xdajvzqmg159ytcx77p; csrftoken=6Hzd0GrKXQAYuo2W3qwDqHQs7MpQdkYc9iauCTUc7hQG9YoT6L0cTsqY2dPM4CNi
X-CSRFToken: OgoFm0sgQTG3lb7Za4Vl6zlfHLuirIZ8RRZWYdVI0kWL0LtWdppUzkVLCcUei0Oe

{
  "email": "idekel.santana@gmail.com",
  "password": "123456"
}

###

PUT localhost:8000/v1/build-profile/profile
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv;csrftoken=JP1OuCkZlrx8PyQVY8CO97XApPuO4OPOv9Bm7nmQWubaWfRVUGsay7PIT6ZaX9ha
Content-Type: application/json
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "bio_title": "Nice instructor",
  "bio": "Son long text",
  "music": "Son long text"
}

###

POST localhost:8000/v1/forgot-password/
Content-Type: application/json

{
  "email": "idekel.santana@gmail.com"
}

###

PUT localhost:8000/v1/forgot-password/?token={token}
Content-Type: application/json

{
  "password": "minuevopassword"
}

###

POST localhost:8000/v1/upload_avatar/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

Body: form-data
Key: avatar
Value: file to upload

###

POST localhost:8000/v1/referral_email/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "email": "luisllave12357@gmail.com"
}

###

PUT localhost:8000/v1/student-details/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "instrument": "flaute",
  "skill_level": "basic",
  "lesson_place": "home",
  "lesson_duration": "90 mins"
}

###

GET localhost:8000/v1/student-details/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv

###

POST localhost:8000/v1/create-students/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

[
	{
		"name": "Joseph",
		"age": 31,
		"instrument": "flaute",
		"skill_level": "basic",
		"lesson_place": "home",
		"lesson_duration": "ninety"
	},
	{
		"name": "Lucy",
		"age": 22,
		"instrument": "piano",
		"skill_level": "basic",
		"lesson_place": "home",
		"lesson_duration": "ninety"
	}
]

###

GET localhost:8000/v1/get-students/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv

###

POST localhost:8000/v1/education/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv
X-CSRFToken: yfmsbIDJlhHYk4m1kQh8r445PNfrBVPekzW0OtFAWkl0rLn1go7uQ4Wdj4KNughA

{
  "school": "Hopkins",
  "graduationYear": 2003,
  "degreeType": "certification",
  "fieldOfStudy": "Math",
  "schoolLocation": "Utah"
}

###

GET localhost:8000/v1/education/
Cookie: sessionid=9396ti9t47fzumbr3kp67l9l1x96rzsv

###
