# Generated by Django 2.2.3 on 2019-07-05 21:00
from django.contrib.postgres.operations import HStoreExtension, CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        CreateExtension('postgis'),
    ]
