# Generated by Django 2.2.3 on 2019-09-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190907_1200'),
        ('core', '0002_auto_20190910_1841'),
    ]

    operations = [
    ]
