# Generated by Django 2.2.3 on 2019-09-13 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190912_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
