# Generated by Django 2.2.3 on 2019-09-20 16:08

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190913_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_token',
            field=models.CharField(blank=True, default=core.models.generate_token, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
