# Generated by Django 2.2.3 on 2019-09-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_restore_referral_token_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('lesson', 'lesson')], max_length=50)),
                ('status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable'), ('used', 'used')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to=settings.AUTH_USER_MODEL)),
                ('user_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_benefits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
