# Generated by Django 2.2.6 on 2020-01-23 23:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_providerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
