# Generated by Django 2.2.6 on 2020-02-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_token',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
