# Generated by Django 2.2.6 on 2020-02-15 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200206_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbenefits',
            old_name='user',
            new_name='beneficiary',
        ),
        migrations.RenameField(
            model_name='userbenefits',
            old_name='user_origin',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='userbenefits',
            name='benefit_qty',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbenefits',
            name='depends_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependants', to='core.UserBenefits'),
        ),
        migrations.AddField(
            model_name='userbenefits',
            name='source',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userbenefits',
            name='benefit_type',
            field=models.CharField(choices=[('lesson', 'lesson'), ('amount', 'amount'), ('discount', 'discount')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userbenefits',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('pending', 'pending'), ('used', 'used')], max_length=50),
        ),
    ]
