# Generated by Django 2.2.6 on 2020-03-04 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200303_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbenefits',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependants', to='core.UserBenefits'),
        ),
        migrations.AlterField(
            model_name='userbenefits',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_benefits', to=settings.AUTH_USER_MODEL),
        ),
    ]
