# Generated by Django 2.2.6 on 2020-08-25 20:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200304_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=150)),
                ('schedule', models.DateTimeField()),
                ('executed', models.BooleanField(blank=True, default=False)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
