# Generated by Django 2.2.6 on 2020-09-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scheduledemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledEmail',
            new_name='ScheduledTask',
        ),
    ]
