# Generated by Django 2.2.6 on 2020-09-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200930_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='limit_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
