# Generated by Django 2.2.3 on 2019-07-17 06:00

import accounts.models
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_directory_path)),
                ('hearAboutUs', models.CharField(blank=True, choices=[('Google', 'Google'), ('Google', 'Google')], max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('bio_title', models.CharField(blank=True, max_length=250, null=True)),
                ('bio_description', models.TextField(blank=True, null=True)),
                ('social_media_accounts', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('english', 'english'), ('spanish', 'spanish')], max_length=100), blank=True, null=True, size=None)),
                ('music', models.TextField(blank=True, null=True)),
                ('job_prefs_one_student', models.BooleanField(default=False)),
                ('job_prefs_small_groups', models.BooleanField(default=False)),
                ('job_prefs_large_groups', models.BooleanField(default=False)),
                ('job_prefs_children', models.BooleanField(default=False)),
                ('job_prefs_teens', models.BooleanField(default=False)),
                ('job_prefs_adults', models.BooleanField(default=False)),
                ('job_prefs_seniors', models.BooleanField(default=False)),
                ('qualif_certified_teacher', models.BooleanField(default=False)),
                ('qualif_music_therapy', models.BooleanField(default=False)),
                ('qualif_music_production', models.BooleanField(default=False)),
                ('qualif_ear_training', models.BooleanField(default=False)),
                ('qualif_conducting', models.BooleanField(default=False)),
                ('qualif_virtuoso_recognition', models.BooleanField(default=False)),
                ('qualif_performance', models.BooleanField(default=False)),
                ('qualif_music_theory', models.BooleanField(default=False)),
                ('qualif_young_children_experience', models.BooleanField(default=False)),
                ('qualif_repertoire_selection', models.BooleanField(default=False)),
                ('place_lessons_home', models.BooleanField(default=False)),
                ('place_lessons_studio', models.BooleanField(default=False)),
                ('place_lessons_online', models.BooleanField(default=False)),
                ('rates_thirty_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rates_forty_five_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rates_sixty_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rates_ninety_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_directory_path)),
                ('hearAboutUs', models.CharField(blank=True, choices=[('Google', 'Google'), ('Google', 'Google')], max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_directory_path)),
                ('hearAboutUs', models.CharField(blank=True, choices=[('Google', 'Google'), ('Google', 'Google')], max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.Parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_type', models.CharField(choices=[('main', 'main'), ('mobile', 'mobile')], max_length=100)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorInstruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='instruments',
            field=models.ManyToManyField(through='accounts.InstructorInstruments', to='instruments.Instrument'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('from_month', models.CharField(blank=True, choices=[('january', 'january'), ('february', 'february'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], max_length=100, null=True)),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_month', models.CharField(blank=True, choices=[('january', 'january'), ('february', 'february'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], max_length=100, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('still_work_here', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('degree_type', models.CharField(blank=True, choices=[('associate', 'Associate Degree'), ('bachelors', "Bachelor's Degree"), ('graduate', 'Graduate Degreee'), ('professional', 'Professional Degree'), ('certification', 'Certification'), ('other', 'Other')], max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('school_location', models.CharField(blank=True, max_length=100, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], max_length=10)),
                ('schedule', models.CharField(choices=[('8AM-10AM', '8AM-10AM'), ('10AM-12PM', '10AM-12PM'), ('12PM-3PM', '12PM-3PM'), ('3PM-6PM', '3PM-6PM')], max_length=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(choices=[('home', 'home'), ('billing', 'billing'), ('studio', 'studio')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
