# Generated by Django 2.2.3 on 2019-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190821_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='lat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='instructor',
            name='long',
            field=models.CharField(default='', max_length=50),
        ),
    ]
