# Generated by Django 2.2.3 on 2019-08-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190824_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='schedule',
        ),
        migrations.AddField(
            model_name='availability',
            name='from1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='availability',
            name='to',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='InstructorPlaceForLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField()),
                ('studio', models.BooleanField()),
                ('online', models.BooleanField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorLessonSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_student', models.BooleanField()),
                ('small_groups', models.BooleanField()),
                ('large_groups', models.BooleanField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorLessonRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mins30', models.FloatField()),
                ('mins45', models.FloatField()),
                ('mins60', models.FloatField()),
                ('mins90', models.FloatField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.BooleanField()),
                ('teens', models.BooleanField()),
                ('adults', models.BooleanField()),
                ('seniors', models.BooleanField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAdditionalQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certified_teacher', models.BooleanField()),
                ('music_therapy', models.BooleanField()),
                ('music_production', models.BooleanField()),
                ('ear_training', models.BooleanField()),
                ('conducting', models.BooleanField()),
                ('virtuoso_recognition', models.BooleanField()),
                ('performance', models.BooleanField()),
                ('music_theory', models.BooleanField()),
                ('young_children_experience', models.BooleanField()),
                ('repertoire_selection', models.BooleanField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
            ],
        ),
    ]
