# Generated by Django 2.2.3 on 2019-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190826_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('undisclosed', 'undisclosed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('undisclosed', 'undisclosed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('undisclosed', 'undisclosed')], max_length=100, null=True),
        ),
    ]
