# Generated by Django 2.2.3 on 2019-09-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190907_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='hear_about_us',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='hear_about_us',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hear_about_us',
        ),
    ]
