# Generated by Django 2.2.3 on 2019-09-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190909_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='parent',
            name='lat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='lng',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='lat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='lng',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
