# Generated by Django 2.2.3 on 2019-09-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190910_1207'),
        ('accounts', '0006_auto_20190910_2035'),
    ]

    operations = [
    ]
