# Generated by Django 2.2.3 on 2019-09-14 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20190911_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_verified_at',
            new_name='verified_at',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
