# Generated by Django 2.2.3 on 2019-09-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190914_1030'),
        ('accounts', '0010_auto_20190911_1219'),
    ]

    operations = [
    ]
