# Generated by Django 2.2.3 on 2019-09-27 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_merge_20190920_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='bio',
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('basic', 'basic'), ('advanced', 'advanced')], max_length=50)),
                ('lesson_place', models.CharField(choices=[('home', 'home'), ('studio', 'studio'), ('online', 'online')], max_length=50)),
                ('lesson_duration', models.CharField(choices=[('thirty', 'thirty'), ('forty five', 'forty five'), ('sixty', 'sixty'), ('ninety', 'ninety')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.Instrument')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.Student')),
            ],
        ),
    ]
