# Generated by Django 2.2.3 on 2019-09-16 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_set_refferal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='referral_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='referral_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='referral_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
