# Generated by Django 2.2.3 on 2019-10-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190927_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='studio_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='travel_distance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
