# Generated by Django 2.2.3 on 2019-10-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191004_1651'),
        ('accounts', '0013_auto_20191002_1317'),
    ]

    operations = [
    ]
