# Generated by Django 2.2.3 on 2019-09-16 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_restore_referral_token_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('lesson', 'lesson')], max_length=50)),
                ('status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable'), ('used', 'used')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='accounts.Student')),
                ('user_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_studentbenefits_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('lesson', 'lesson')], max_length=50)),
                ('status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable'), ('used', 'used')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='accounts.Parent')),
                ('user_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_parentbenefits_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('lesson', 'lesson')], max_length=50)),
                ('status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable'), ('used', 'used')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='accounts.Instructor')),
                ('user_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_instructorbenefits_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
