# Generated by Django 2.2.3 on 2019-10-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20191002_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='student',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TiedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tied_students', to='accounts.Parent')),
            ],
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='tied_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tied_student_details', to='accounts.TiedStudent'),
        ),
    ]
