# Generated by Django 2.2.3 on 2019-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191008_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='lesson_duration',
            field=models.CharField(choices=[('30 mins', '30 mins'), ('45 mins', '45 mins'), ('60 mins', '60 mins'), ('90 mins', '90 mins')], max_length=50),
        ),
    ]
