# Generated by Django 2.2.6 on 2019-10-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191009_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='lesson_duration',
            new_name='lessonDuration',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='lesson_place',
            new_name='lessonPlace',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='skill_level',
            new_name='skillLevel',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='tied_student',
            new_name='tiedStudent',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
