# Generated by Django 2.2.6 on 2019-10-14 17:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20191011_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='lesson_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
