# Generated by Django 2.2.3 on 2019-10-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20191011_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.Instructor'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='accounts.Instructor'),
        ),
    ]
