# Generated by Django 2.2.6 on 2019-10-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_instructor_lesson_size'),
        ('accounts', '0019_auto_20191014_1841'),
    ]

    operations = [
    ]
