# Generated by Django 2.2.6 on 2019-10-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20191014_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.Instructor'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='accounts.Instructor'),
        ),
    ]
