# Generated by Django 2.2.3 on 2019-10-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20191014_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='lessonDuration',
            new_name='lesson_duration',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='lessonPlace',
            new_name='lesson_place',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='skillLevel',
            new_name='skill_level',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='tiedStudent',
            new_name='tied_student',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
