# Generated by Django 2.2.6 on 2019-10-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20191015_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='certified_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='conducting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='ear_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='music_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='music_theory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='music_therapy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='repertoire_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='virtuoso_recognition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoradditionalqualifications',
            name='young_children_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoragegroup',
            name='adults',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoragegroup',
            name='children',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoragegroup',
            name='seniors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructoragegroup',
            name='teens',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructorlessonsize',
            name='large_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructorlessonsize',
            name='one_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructorlessonsize',
            name='small_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructorplaceforlessons',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructorplaceforlessons',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructorplaceforlessons',
            name='studio',
            field=models.BooleanField(default=False),
        ),
    ]
