# Generated by Django 2.2.6 on 2019-11-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20191104_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
