# Generated by Django 2.2.6 on 2019-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='profile completed'),
        ),
    ]
