# Generated by Django 2.2.6 on 2020-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_instructor_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='bg_status',
            field=models.CharField(blank=True, choices=[('not verified', 'not verified'), ('pending', 'pending'), ('verified', 'verified'), ('warning', 'warning')], default='not verified', max_length=100),
        ),
    ]
