# Generated by Django 2.2.6 on 2020-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_instructor_bg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='instructor',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parent',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='bg_status',
            field=models.CharField(blank=True, choices=[('NOT_VERIFIED', 'NOT_VERIFIED'), ('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('WARNING', 'WARNING')], default='NOT_VERIFIED', max_length=100),
        ),
    ]
