# Generated by Django 2.2.6 on 2020-01-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_instructor_bg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bg_status',
            field=models.CharField(blank=True, choices=[('NOT_VERIFIED', 'NOT_VERIFIED'), ('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('WARNING', 'WARNING')], default='NOT_VERIFIED', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='studentdetails',
            constraint=models.UniqueConstraint(fields=('user', 'tied_student'), name='unique_student'),
        ),
    ]
