# Generated by Django 2.2.6 on 2020-01-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20200110_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='completed',
            new_name='complete',
        ),
    ]
