# Generated by Django 2.2.6 on 2020-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200117_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='bg_status',
            field=models.CharField(blank=True, choices=[('NOT_VERIFIED', 'NOT_VERIFIED'), ('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('WARNING', 'WARNING')], default='NOT_VERIFIED', max_length=100, verbose_name='Background check status'),
        ),
    ]
