# Generated by Django 2.2.6 on 2020-02-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20200128_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
