# Generated by Django 2.2.6 on 2020-04-20 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0036_affiliate_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('user', 'number')},
        ),
    ]
