# Generated by Django 2.2.6 on 2020-04-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200420_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='qualifications',
        ),
    ]
