# Generated by Django 2.2.6 on 2020-05-08 21:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200415_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.video_directory_path),
        ),
    ]
