# Generated by Django 2.2.6 on 2020-05-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200415_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
