# Generated by Django 2.2.6 on 2020-06-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20200523_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='video',
            field=models.URLField(blank=True, default='', verbose_name='URL of video file'),
        ),
    ]
