# Generated by Django 2.2.6 on 2020-06-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20200601_1313'),
        ('accounts', '0041_auto_20200529_0850'),
    ]

    operations = [
    ]
