# Generated by Django 2.2.6 on 2020-06-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_merge_20200608_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.Instructor'),
        ),
    ]
