# Generated by Django 2.2.6 on 2020-07-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20200609_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
