# Generated by Django 2.2.6 on 2020-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20200714_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
