# Generated by Django 2.2.6 on 2020-10-01 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20200810_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SpecialNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_needs', to='accounts.StudentDetails')),
            ],
        ),
    ]
