# Generated by Django 2.2.6 on 2020-10-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20201001_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='interviewed',
            new_name='screened',
        ),
    ]
