# Generated by Django 2.2.6 on 2019-11-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='displayed',
        ),
    ]
