# Generated by Django 2.2.6 on 2020-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_offer_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='free_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='percent_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
