# Generated by Django 2.2.6 on 2020-10-13 19:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0050_auto_20201008_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorRegularAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')])),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_availability', to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorParticularAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particular_availability', to='accounts.Instructor')),
            ],
        ),
    ]
