# Generated by Django 2.2.6 on 2020-11-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorparticularavailability',
            options={'verbose_name_plural': 'Instructor Particular Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='instructorregularavailability',
            options={'verbose_name_plural': 'Instructor Regular Availabilities'},
        ),
    ]
