# Generated by Django 2.2.6 on 2019-12-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_affiliate'),
        ('payments', '0001_initial'),
        ('lesson', '0003_auto_20191009_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=9)),
                ('lesson_rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('paid', 'paid')], default='requested', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='accounts.Instructor')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='accounts.Parent')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='payments.Payment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='accounts.Student')),
            ],
        ),
    ]
