# Generated by Django 2.2.6 on 2019-12-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_instructor_completed'),
        ('lesson', '0004_auto_20191216_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='students',
            field=models.ManyToManyField(to='accounts.TiedStudent'),
        ),
    ]
