# Generated by Django 2.2.6 on 2019-12-18 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_lessonrequest_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
