# Generated by Django 2.2.6 on 2019-12-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_lessonrequest_max_travel_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='max_travel_distance',
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='travel_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
