# Generated by Django 2.2.6 on 2019-12-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_instructor_completed'),
        ('lesson', '0008_auto_20191219_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('seen', 'seen'), ('no seen', 'no seen')], default='no seen', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.Instructor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='lesson.LessonRequest')),
            ],
        ),
    ]
