# Generated by Django 2.2.6 on 2020-01-08 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200101_1833'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0009_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED'), ('CLOSED', 'CLOSED')], default='ACTIVE', max_length=100),
        ),
        migrations.CreateModel(
            name='LessonBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=9)),
                ('status', models.CharField(choices=[('requested', 'requested'), ('cancelled', 'cancelled')], default='requested', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='lesson.Application')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_bookings', to='payments.Payment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='lesson.LessonRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
