# Generated by Django 2.2.6 on 2020-01-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_auto_20200109_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
