# Generated by Django 2.2.6 on 2020-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_auto_20200109_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
