# Generated by Django 2.2.6 on 2020-03-03 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_gradedlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
