# Generated by Django 2.2.6 on 2020-05-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_lessonbooking_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('scheduled_status', models.CharField(choices=[('requested', 'requested'), ('changed', 'changed'), ('agreed', 'agreed')], default='requested', max_length=50)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.LessonBooking')),
            ],
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='students',
            field=models.ManyToManyField(blank=True, to='accounts.TiedStudent'),
        ),
        migrations.DeleteModel(
            name='GradedLesson',
        ),
    ]
