# Generated by Django 2.2.6 on 2020-05-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_auto_20200505_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbooking',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('paid', 'paid'), ('trial', 'trial'), ('cancelled', 'cancelled')], default='requested', max_length=50),
        ),
    ]
