# Generated by Django 2.2.6 on 2020-05-08 16:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_auto_20200505_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='scheduled_status',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('missed', 'missed'), ('complete', 'complete')], default='scheduled', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='lessonbooking',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('paid', 'paid'), ('trial', 'trial'), ('cancelled', 'cancelled')], default='requested', max_length=50),
        ),
    ]
