# Generated by Django 2.2.6 on 2020-06-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0016_auto_20200508_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
