# Generated by Django 2.2.6 on 2020-05-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0017_auto_20200519_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='trial_proposed_timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
