# Generated by Django 2.2.6 on 2020-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0018_auto_20200525_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='scheduled_timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
