# Generated by Django 2.2.6 on 2020-06-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0017_auto_20200602_1312'),
        ('lesson', '0019_auto_20200526_1035'),
    ]

    operations = [
    ]
