# Generated by Django 2.2.6 on 2020-06-10 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0020_merge_20200608_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_booking_lessons', to='lesson.LessonRequest'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.LessonBooking'),
        ),
    ]
