# Generated by Django 2.2.6 on 2020-06-15 23:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20200609_1552'),
        ('lesson', '0021_auto_20200609_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='request',
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='accounts.Instructor'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.Instructor'),
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='lesson.LessonRequest'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.LessonBooking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='scheduled_datetime',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='scheduled_timezone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lessonbooking',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lesson.Application'),
        ),
    ]
