# Generated by Django 2.2.6 on 2020-07-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20200609_1552'),
        ('lesson', '0022_auto_20200615_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='students',
            field=models.ManyToManyField(blank=True, to='accounts.TiedStudent'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='scheduled_timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('missed', 'missed'), ('complete', 'complete')], default='pending', max_length=50),
        ),
    ]
