# Generated by Django 2.2.6 on 2020-07-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0023_auto_20200708_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='lesson.Instrument'),
        ),
    ]
