# Generated by Django 2.2.6 on 2020-08-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20200810_1335'),
        ('lesson', '0023_auto_20200708_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorRefuseLessonRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_refuses', to='accounts.Instructor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuses', to='lesson.LessonRequest')),
            ],
        ),
    ]
