# Generated by Django 2.2.6 on 2020-08-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20200810_1335'),
        ('lesson', '0024_instructorrefuselessonrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAcceptanceLessonRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_requests', to='accounts.Instructor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='lesson.LessonRequest')),
            ],
            options={
                'unique_together': {('instructor', 'request')},
            },
        ),
        migrations.DeleteModel(
            name='InstructorRefuseLessonRequest',
        ),
    ]
