# Generated by Django 2.2.6 on 2020-09-09 03:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0025_auto_20200820_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='trial_availability_schedule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
