# Generated by Django 2.2.6 on 2020-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0026_lessonrequest_trial_availability_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
