# Generated by Django 2.2.6 on 2019-11-09 19:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_providerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheckRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preliminary', 'preliminary'), ('requested', 'requested'), ('complete', 'complete'), ('cancelled', 'cancelled')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_check_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundCheckStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_step', to='background_checks.BackgroundCheckStep')),
                ('provider_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProviderRequest')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='background_checks.BackgroundCheckRequest')),
            ],
        ),
    ]
