# Generated by Django 2.2.6 on 2020-01-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_instructor_completed'),
        ('background_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcheckrequest',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bg_check_requests', to='accounts.Instructor'),
        ),
        migrations.AlterField(
            model_name='backgroundcheckrequest',
            name='status',
            field=models.CharField(choices=[('preliminary', 'preliminary'), ('requested', 'requested'), ('complete', 'complete'), ('cancelled', 'cancelled')], default='preliminary', max_length=100),
        ),
    ]
