# Generated by Django 2.2.6 on 2020-01-07 00:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_checks', '0003_backgroundcheckrequest_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcheckrequest',
            name='provider_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='backgroundcheckrequest',
            name='observation',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
