# Generated by Django 2.2.6 on 2020-01-10 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200109_1544'),
        ('background_checks', '0004_auto_20200106_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundcheckrequest',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Payment'),
        ),
    ]
