# Generated by Django 2.2.6 on 2020-12-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_checks', '0005_backgroundcheckrequest_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundcheckstep',
            name='previous_step',
        ),
        migrations.RemoveField(
            model_name='backgroundcheckstep',
            name='provider_request',
        ),
        migrations.RemoveField(
            model_name='backgroundcheckstep',
            name='request',
        ),
        migrations.DeleteModel(
            name='BackgroundCheckRequest',
        ),
        migrations.DeleteModel(
            name='BackgroundCheckStep',
        ),
    ]
