# Generated by Django 2.2.6 on 2019-12-06 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referencerequest',
            unique_together={('user', 'email')},
        ),
    ]
